version: '3.7'

services:
   mysql:
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: fsetai123
       MYSQL_DATABASE: itau
       MYSQL_USER: fsetai
       MYSQL_PASSWORD: fsetai123

   memcached1:
     image: memcached

   app:
     depends_on:
     - mysql
     - memcached1
     image: japzin/php-app
     deploy:
       replicas: 3
     ports:
     - "8080:8080"
     environment:
       DB_HOST: mysql
       DB_PORT: 3306
       DB_USER: fsetai
       DB_PASS: fsetai123
       DB_NAME: itau
